[[redirects]]
  from = "/api/airtable"
  to = "/.netlify/functions/airtable-proxy"
  status = 200

[[redirects]]
  from = "/api/invite"
  to = "/.netlify/functions/circle-invite"
  status = 200

[[redirects]]
  from = "/api/stripe-sync"
  to = "/.netlify/functions/stripe-sync"
  status = 200

[[redirects]]
  from = "/api/play-live"
  to = "/.netlify/functions/play-live"
  status = 200
